name: publish
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install
      # No test case, yet.
      # - run: npm test
      - run: npm publish --access public

        # NPM PUBLISH TOKEN
        env:
          NODE_AUTH_TOKEN: ${{ NPM_PUBLISH_TOKEN }}
